### ISSUE TITLE
how to use the python script

### ISSUE THREAD

**Issue by Nes-player4Life** [RWeick/FCD-0003.1S-Xplorer64#1]
I'm looking to see if my firmware that I downloaded from my cart last year will scramble/unscramble.
How exactly do I use the scripts?

**Comment by RWeick** [comment]
The scripts expect that you’re providing a combined, scrambled or unscrambled file, but they do split the file and then work on each half as they would be when dumped from a chip. Are your files the individual dumps from each chip? Modifying the code to work with them already split wouldn’t be too hard

**Comment by Nes-player4Life** [comment]
turns out i was using python 2.7.X. updated to the latest my system will handle and my rip scrambles! 
looks great! 

I managed to somehow rip the xplorer orange in conjunction with a gameshark and sani cart. It was very wonky and it only appeared to rip correctly once so I have been curious if its data was complete

**Comment by RWeick** [comment]
Well I’m glad you got it figured out, and that everything worked for you!

**Comment by Nes-player4Life** [comment]
Thank you so much for helping preserve these old devices.
